apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  name: remote-cluster
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: "staging"
    provider: "minikube"
    non-prod: "true"
type: Opaque
stringData:
  name: remote-cluster
  server: https://192.168.58.2:8443
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }