apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-shared-resources
  namespace: argocd
spec:
  destination:
    namespace: demo-shared-resources
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: guestbook
    repoURL: "https://github.com/kevingigiano/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResources=true