apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-staging
  namespace: argocd
spec:
  destination:
    namespace: guestbook-staging
    server: "https://192.168.58.2:8443"
  project: default
  source:
    path: guestbook
    repoURL: "https://github.com/kevingigiano/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true